import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/context";
import { Sidebar } from "@/components/sidebar";
import { PickProvider } from "@/components/Contexts/ticketContext";
import { UserProvider } from "@/components/Contexts/userContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
       <PickProvider>
        <ThemeProvider>
          <Sidebar />
          {children}
        </ThemeProvider>
      </PickProvider>
      </UserProvider>
      </body>
    </html>
  );
}
